name: adopteur.se
favicon: null
layout_spectrum: 0.7726085183676332
typography_spectrum: 0.7488294972572476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49598517431877553
  lightness: 0.09930360992439091
  saturation: 0.4451104167383164
  rhythmicContrast: 0.3194601181894541
purpose: []
